source 'https://rubygems.org'
# ruby '1.9.3'
gem 'logger'
gem 'sinatra'
gem 'pry'
gem 'pry-debugger'
gem 'addressable', require: 'addressable/uri'
gem 'builder'
gem 'capybara'
gem 'poltergeist', "1.4.1", require: 'capybara/poltergeist'
gem 'thin'
gem 'sinatra-contrib'
gem 'slim'
gem 'mongoid','3.1.5'
gem 'bson_ext'
gem 'sinatra-websocket'
gem 'coffee-script'

